[package]
authors = ["Andronik Ordian <write@reusable.software>"]
name = "lazy_transform_sync"
version = "0.1.0"

[dependencies]
crossbeam-epoch = "0.2.0"
either = "1.4.0"
lazy-init = "0.2.0"

[dev-dependencies]
crossbeam = "0.3.0"